### ISSUE TITLE
Add support for `--watch` option

### ISSUE THREAD

**Issue by ChristopherHaws** [rafaelldi/tye-plugin#128]
`tye run` supports passing `--watch` as an argument. It would be awesome to be able to do this with this plugin!
https://github.com/dotnet/tye/blob/main/docs/reference/commandline/tye-run.md

Thanks for the awesome plugin!

**Comment by rafaelldi** [comment]
Thank you for the feedback!

I will try to add this in the next release.

**Comment by rafaelldi** [comment]
Hello @ChristopherHaws. New version is available now.
