### ISSUE TITLE
Add support for the EAP version of Rider

### ISSUE THREAD

**Issue by ChristopherHaws** [rafaelldi/tye-plugin#141]
The latest version (0.4.0) doesn't appear to support the EAP version of Rider (but v0.3.0 did). When I try to install the updated plugin, I get the following error:
![image](https://user-images.githubusercontent.com/5934505/162058632-d5e3e392-a566-414a-b02e-8dfa64a851f8.png)

Thanks!

**Comment by rafaelldi** [comment]
Hello @ChristopherHaws. 
Sorry, but there are some compatibility issues. I can only target 2021.3 or 2022.1 release, so I'm planning to publish a new version with a new release of Rider.
